Roles
Karenduque/primerProyecto pull request #4
Opened 2021-03-10 21:57 UTC by marisleidy

Se agrego escenario de prueba "Correct Login as User"

2021-03-10 22:24 UTC, Karenduque requested changes

2021-03-10 22:24 UTC, Karenduque commented on niikiis_e2e_automation/configuration/configuration-dev.robot
> +${PASS_ADMIN}   123456
por fa no pongas la contraseña nunca en archivos publicos :p

2021-03-10 22:24 UTC, Karenduque commented on niikiis_e2e_automation/specs/login.robot
> +  Then the Home is visible for the User
has lo mismo para author asi sea igual que user

2021-03-10 22:40 UTC, marisleidy commented on niikiis_e2e_automation/configuration/configuration-dev.robot
> +${PASS_ADMIN}   123456
Ya quedo borrado y actualizado

2021-03-10 22:41 UTC, marisleidy commented on niikiis_e2e_automation/specs/login.robot
> +  Then the Home is visible for the User
Hice un escenario outline estoy pendiente si crees que esta bien.

2021-03-11 14:49 UTC, Karenduque requested changes
1, Resuelve los comentarios
2, Dale click al boton de "resolver comentario"
3, Enviame de nuevo el pr
4, En el revisro me pones a mi
y te asignas el pr a ti misma porque es de tu propiedad

2021-03-11 14:49 UTC, Karenduque commented on niikiis_e2e_automation/specs/login.robot
> +   Autor
esta en la traduccion al ingles ? creo que es esta: Author

2021-03-11 14:49 UTC, Karenduque commented on niikiis_e2e_automation/specs/login.robot
> +Correct Login template
creo que podrias poner simplemente : the user session is opened as Author/User

2021-03-11 14:49 UTC, Karenduque commented on niikiis_e2e_automation/specs/login.robot
> +Correct Login as User or Autor
creo que podrias poner simplemente : the user session is opened as Author/User

2021-03-11 18:55 UTC, marisleidy commented on niikiis_e2e_automation/specs/login.robot
> +   Autor
Quedo corregido!!

2021-03-11 18:57 UTC, marisleidy commented on niikiis_e2e_automation/specs/login.robot
> +Correct Login template
Ya le cambie el nombre al template.!

2021-03-12 11:15 UTC, Karenduque approved these changes

2021-03-12 11:15 UTC, merged