Categories
Karenduque/primerProyecto pull request #5
Opened 2021-03-19 21:47 UTC by marisleidy

Test Case Create Categorie.

2021-03-20 10:50 UTC, Karenduque requested changes

2021-03-20 20:34 UTC, marisleidy commented on niikiis_e2e_automation/configuration/configuration-dev.robot
> +${PASS_ADMIN}   123456
Corregido

2021-03-20 20:34 UTC, marisleidy commented on niikiis_e2e_automation/pagesobjects/home-page.robot
> +
Corregido

2021-03-20 20:35 UTC, marisleidy commented on niikiis_e2e_automation/specs/create-categories.robot
> +Create Categories as ADMIN
corregido

2021-03-20 20:36 UTC, marisleidy commented on niikiis_e2e_automation/specs/create-categories.robot
> +  Given that it is required to create category
Corregido :)

2021-03-20 20:37 UTC, marisleidy commented on niikiis_e2e_automation/pagesobjects/configuration-page.robot
> +${configurationIcon}   XPath://*[@id="root"]/div/div[2]/nav/div[2]/a[2]
Corregido. Toco utilizar la opción de "contains". pero ya funciona todo 👍

2021-03-30 04:48 UTC, marisleidy commented on niikiis_e2e_automation/facades/login-facade.robot
> +that I login as administrator
Corregido!!

2021-03-30 22:19 UTC, marisleidy commented on niikiis_e2e_automation/pagesobjects/configuration-page.robot
> +*** Settings ***
Solucionado!!!

2021-03-30 22:19 UTC, marisleidy commented on niikiis_e2e_automation/specs/create-categories.robot
> +  When click the configuration icon
Solucionado!!!

2021-03-31 15:36 UTC, Karenduque approved these changes

2021-03-31 15:37 UTC, merged